/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manager;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Objects;
import javax.swing.Icon;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import manager.renderer.CompressionLevelListCellRenderer;
import measure.format.binary.ByteUnitFormat;

/**
 *
 * @author Mosblinker
 */
public class ExternalLocationPanel extends javax.swing.JPanel {
    /**
     * 
     */
    public static final String PROFILE_PICTURE_ICON_PROPERTY_CHANGED = 
            "ProfileIconPropertyChanged";
    /**
     * 
     */
    public static final String ACCOUNT_NAME_PROPERTY_CHANGED = 
            "AccountNamePropertyChanged";
    /**
     * 
     */
    public static final String SPACE_USED_PROPERTY_CHANGED = 
            "SpaceUsedPropertyChanged";
    /**
     * 
     */
    public static final String SPACE_FREE_PROPERTY_CHANGED = 
            "SpaceFreePropertyChanged";
    /**
     * 
     */
    public static final String BROWSE_BUTTON_SHOWN_PROPERTY_CHANGED = 
            "BrowseButtonShownPropertyChanged";
    /**
     * 
     */
    public static final String FILE_COMPRESSION_ENABLED_PROPERTY_CHANGED = 
            "FileCompressionEnabledPropertyChanged";
    /**
     * 
     */
    public static final String FILE_COMPRESSION_LEVEL_PROPERTY_CHANGED = 
            "FileCompressionLevelPropertyChanged";
    /**
     * 
     */
    public static final String LOG_OUT_COMMAND = "LogOut";
    /**
     * 
     */
    public static final String BROWSE_COMMAND = "Browse";
    /**
     * These are the available compression levels for 7-Zip.
     */
    private static final Integer[] COMPRESSION_LEVELS = {
        0, 1, 3, 5, 7, 9
    };
    /**
     * Creates new form ExternalLocationPanel
     */
    public ExternalLocationPanel() {
        initComponents();
        dbFileField.getDocument().addDocumentListener(new Handler());
        compressionLevelCombo.setSelectedItem(compressionLevel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dataPanel = new javax.swing.JPanel();
        pfpLabel = new components.JThumbnailLabel();
        accountNameLabel = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        spaceUsedLabel = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        spaceFreeLabel = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        javax.swing.Box.Filler filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        compressionToggle = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        compressionLevelCombo = new javax.swing.JComboBox<>();
        filePanel = new javax.swing.JPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.Box.Filler filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        dbFileField = new javax.swing.JTextField();
        dbBrowseFiller = new javax.swing.Box.Filler(new java.awt.Dimension(7, 0), new java.awt.Dimension(7, 0), new java.awt.Dimension(7, 32767));
        browseButton = new javax.swing.JButton();

        dataPanel.setLayout(new java.awt.GridBagLayout());

        pfpLabel.setImageScaleMode(components.JThumbnailLabel.ALWAYS_SCALE_MAINTAIN_ASPECT_RATIO);
        pfpLabel.setThumbnailBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pfpLabel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pfpLabelPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 12);
        dataPanel.add(pfpLabel, gridBagConstraints);

        accountNameLabel.setFont(accountNameLabel.getFont().deriveFont(accountNameLabel.getFont().getStyle() | java.awt.Font.BOLD));
        accountNameLabel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                accountNameLabelPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 0);
        dataPanel.add(accountNameLabel, gridBagConstraints);

        jLabel1.setLabelFor(spaceUsedLabel);
        jLabel1.setText("Space Used:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 12);
        dataPanel.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 0);
        dataPanel.add(spaceUsedLabel, gridBagConstraints);

        jLabel5.setLabelFor(spaceFreeLabel);
        jLabel5.setText("Space Free:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 12);
        dataPanel.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 0);
        dataPanel.add(spaceFreeLabel, gridBagConstraints);

        logOutButton.setText("Log Out");
        logOutButton.setActionCommand(LOG_OUT_COMMAND);
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        dataPanel.add(logOutButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 0.75;
        dataPanel.add(filler1, gridBagConstraints);

        compressionToggle.setText("Compress File");
        compressionToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compressionToggleActionPerformed(evt);
            }
        });

        jLabel3.setLabelFor(compressionLevelCombo);
        jLabel3.setText("Compression Level:");

        compressionLevelCombo.setModel(new javax.swing.DefaultComboBoxModel<>(COMPRESSION_LEVELS));
        compressionLevelCombo.setEnabled(false);
        compressionLevelCombo.setRenderer(new CompressionLevelListCellRenderer());
        compressionLevelCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compressionLevelComboActionPerformed(evt);
            }
        });

        filePanel.setLayout(new javax.swing.BoxLayout(filePanel, javax.swing.BoxLayout.X_AXIS));

        jLabel2.setLabelFor(dbFileField);
        jLabel2.setText("File:");
        filePanel.add(jLabel2);
        filePanel.add(filler2);
        filePanel.add(dbFileField);
        filePanel.add(dbBrowseFiller);

        browseButton.setText("Browse");
        browseButton.setActionCommand(BROWSE_COMMAND);
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });
        filePanel.add(browseButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(compressionToggle)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compressionLevelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(dataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(compressionLevelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(compressionToggle))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        fireActionEvent(evt);
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        fireActionEvent(evt);
    }//GEN-LAST:event_browseButtonActionPerformed

    private void compressionToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compressionToggleActionPerformed
        setFileCompressionEnabled(compressionToggle.isSelected());
    }//GEN-LAST:event_compressionToggleActionPerformed

    private void compressionLevelComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compressionLevelComboActionPerformed
        int index = Math.max(compressionLevelCombo.getSelectedIndex(),0);
        setFileCompressionLevel(COMPRESSION_LEVELS[index]);
    }//GEN-LAST:event_compressionLevelComboActionPerformed

    private void pfpLabelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pfpLabelPropertyChange
        if ("icon".equals(evt.getPropertyName()))
            firePropertyChange(PROFILE_PICTURE_ICON_PROPERTY_CHANGED,evt.getOldValue(),
                    evt.getNewValue());
    }//GEN-LAST:event_pfpLabelPropertyChange

    private void accountNameLabelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_accountNameLabelPropertyChange
        if ("text".equals(evt.getPropertyName()))
            firePropertyChange(ACCOUNT_NAME_PROPERTY_CHANGED,evt.getOldValue(),
                    evt.getNewValue());
    }//GEN-LAST:event_accountNameLabelPropertyChange
    /**
     * 
     * @return 
     */
    public Icon getProfilePictureIcon(){
        return pfpLabel.getIcon();
    }
    /**
     * 
     * @param icon 
     */
    public void setProfilePictureIcon(Icon icon){
        pfpLabel.setIcon(icon);
    }
    /**
     * 
     * @return 
     */
    public String getAccountName(){
        return accountNameLabel.getText();
    }
    /**
     * 
     * @param name 
     */
    public void setAccountName(String name){
        accountNameLabel.setText(name);
    }
    /**
     * 
     * @return 
     */
    public Long getSpaceUsed(){
        return spaceUsed;
    }
    /**
     * 
     * @param value 
     */
    public void setSpaceUsed(Long value){
        if (!Objects.equals(value, spaceUsed)){
            Long old = spaceUsed;
            spaceUsed = value;
            firePropertyChange(SPACE_USED_PROPERTY_CHANGED,old,value);
            spaceUsedLabel.setText((value!=null)?byteFormatter.format(value):null);
        }
    }
    /**
     * 
     * @return 
     */
    public Long getSpaceFree(){
        return spaceFree;
    }
    /**
     * 
     * @param value 
     */
    public void setSpaceFree(Long value){
        if (!Objects.equals(value, spaceFree)){
            Long old = spaceFree;
            spaceFree = value;
            firePropertyChange(SPACE_FREE_PROPERTY_CHANGED,old,value);
            spaceFreeLabel.setText((value!=null)?byteFormatter.format(value):null);
        }
    }
    /**
     * 
     * @return 
     */
    public String getFileText(){
        return dbFileField.getText();
    }
    /**
     * 
     * @param text 
     */
    public void setFileText(String text){
        dbFileField.setText(text);
    }
    /**
     * 
     * @return 
     */
    public boolean isBrowseButtonShown(){
        return showBrowse;
    }
    /**
     * 
     * @param shown 
     */
    public void setBrowseButtonShown(boolean shown){
        if (shown != showBrowse){
            showBrowse = shown;
            firePropertyChange(BROWSE_BUTTON_SHOWN_PROPERTY_CHANGED,!shown,shown);
            browseButton.setVisible(shown);
            dbBrowseFiller.setVisible(shown);
        }
    }
    /**
     * 
     * @return 
     */
    public boolean isFileCompressionEnabled(){
        return compressionEnabled;
    }
    /**
     * 
     * @param enabled 
     */
    public void setFileCompressionEnabled(boolean enabled){
        if (enabled != compressionEnabled){
            compressionEnabled = enabled;
            firePropertyChange(FILE_COMPRESSION_ENABLED_PROPERTY_CHANGED,
                    !enabled,enabled);
            compressionToggle.setSelected(enabled);
            compressionLevelCombo.setEnabled(enabled&&isEnabled());
        }
    }
    /**
     * 
     * @return 
     */
    public int getFileCompressionLevel(){
        return compressionLevel;
    }
    /**
     * 
     * @param level 
     */
    public void setFileCompressionLevel(int level){
        if (compressionLevel != level){
            int old = compressionLevel;
            compressionLevel = level;
            firePropertyChange(FILE_COMPRESSION_LEVEL_PROPERTY_CHANGED,old,level);
            if (!Objects.equals(compressionLevelCombo.getSelectedItem(), level))
                compressionLevelCombo.setSelectedItem(level);
        }
    }
    /**
     * 
     * @param l 
     */
    public void addActionListener(ActionListener l){
        if (l != null)
            listenerList.add(ActionListener.class, l);
    }
    /**
     * 
     * @param l 
     */
    public void removeActionListener(ActionListener l){
        listenerList.remove(ActionListener.class, l);
    }
    /**
     * 
     * @return 
     */
    public ActionListener[] getActionListeners(){
        return listenerList.getListeners(ActionListener.class);
    }
    /**
     * 
     * @param evt 
     */
    protected void fireActionEvent(ActionEvent evt){
        if (evt == null)
            return;
        if (evt.getSource() != this)
            evt = new ActionEvent(this,evt.getID(),evt.getActionCommand(),
                    evt.getWhen(),evt.getModifiers());
        for (ActionListener l : getActionListeners()){
            if (l != null)
                l.actionPerformed(evt);
        }
    }
    /**
     * 
     * @param actionCommand 
     */
    protected void fireActionEvent(String actionCommand){
        fireActionEvent(new ActionEvent(this,ActionEvent.ACTION_PERFORMED,
                actionCommand));
    }
    /**
     * 
     * @param l 
     */
    public void addDocumentListener(DocumentListener l){
        if (l != null)
            listenerList.add(DocumentListener.class, l);
    }
    /**
     * 
     * @param l 
     */
    public void removeDocumentListener(DocumentListener l){
        listenerList.remove(DocumentListener.class, l);
    }
    /**
     * 
     * @return 
     */
    public DocumentListener[] getDocumentListeners(){
        return listenerList.getListeners(DocumentListener.class);
    }
    /**
     * This is used to format file sizes when displaying the size of a file.
     */
    private ByteUnitFormat byteFormatter = new ByteUnitFormat(true);
    /**
     * 
     */
    private Long spaceUsed = null;
    /**
     * 
     */
    private Long spaceFree = null;
    /**
     * 
     */
    private boolean showBrowse = true;
    /**
     * 
     */
    private boolean compressionEnabled = false;
    
    private int compressionLevel = 5;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNameLabel;
    private javax.swing.JButton browseButton;
    private javax.swing.JComboBox<Integer> compressionLevelCombo;
    private javax.swing.JCheckBox compressionToggle;
    private javax.swing.JPanel dataPanel;
    private javax.swing.Box.Filler dbBrowseFiller;
    private javax.swing.JTextField dbFileField;
    private javax.swing.JPanel filePanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logOutButton;
    private components.JThumbnailLabel pfpLabel;
    private javax.swing.JLabel spaceFreeLabel;
    private javax.swing.JLabel spaceUsedLabel;
    // End of variables declaration//GEN-END:variables
    /**
     * 
     */
    private class Handler implements DocumentListener{
        @Override
        public void insertUpdate(DocumentEvent evt) {
            for (DocumentListener l : getDocumentListeners()){
                if (l != null)
                    l.insertUpdate(evt);
            }
        }
        @Override
        public void removeUpdate(DocumentEvent evt) {
            for (DocumentListener l : getDocumentListeners()){
                if (l != null)
                    l.removeUpdate(evt);
            }
        }
        @Override
        public void changedUpdate(DocumentEvent evt) {
            for (DocumentListener l : getDocumentListeners()){
                if (l != null)
                    l.changedUpdate(evt);
            }
        }
    }
}
