/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manager;

import java.awt.event.*;
import java.util.Objects;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.text.Position;

/**
 *
 * @author Milo Steier
 */
public class LinkSearchPanel extends JPanel {
    
    public static final String SEARCH_FIND_NEXT_COMMAND = "FindNext";
    
    public static final String SEARCH_FIND_PREVIOUS_COMMAND = "FindPrevious";
    
    public static final String SEARCH_CANCEL_COMMAND = "FindCancel";
    
    public static final String MATCH_SPACES_PROPERTY_CHANGED = "MatchSpacesPropertyChanged";
    
    public static final String MATCH_CASE_PROPERTY_CHANGED = "MatchCasePropertyChanged";
    
    public static final String WRAP_AROUND_PROPERTY_CHANGED = "WrapAroundPropertyChanged";

    /**
     * Creates new form LinkSearchPanel
     */
    public LinkSearchPanel() {
        findNextAction = new FindAction(Position.Bias.Forward);
        findPrevAction = new FindAction(Position.Bias.Backward);
        initComponents();
        Handler handler = new Handler();
        searchField.getDocument().addDocumentListener(handler);
            // The action performed when escape is pressed
        Action searchCancel = new AbstractAction("SearchCancel"){
            @Override
            public void actionPerformed(ActionEvent evt) {
                fireActionPerformed(evt);
            }
        };
        searchCancel.putValue(Action.ACTION_COMMAND_KEY, SEARCH_CANCEL_COMMAND);
        getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT)
                .put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), 
                        searchCancel.getValue(Action.NAME));
        getActionMap().put(searchCancel.getValue(Action.NAME),searchCancel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchPopupMenu = new javax.swing.JPopupMenu();
        searchField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        findButtonPanel = new javax.swing.JPanel();
        findNextButton = new javax.swing.JButton();
        findPreviousButton = new javax.swing.JButton();
        findCancelButton = new javax.swing.JButton();
        settingPanel = new javax.swing.JPanel();
        matchCaseOption = new javax.swing.JCheckBox();
        matchSpacesOption = new javax.swing.JCheckBox();
        findWrapOption = new javax.swing.JCheckBox();

        searchField.setActionCommand(SEARCH_FIND_NEXT_COMMAND);
        searchField.setComponentPopupMenu(searchPopupMenu);
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Find:");

        findButtonPanel.setLayout(new java.awt.GridLayout(3, 1, 0, 7));

        findNextButton.setAction(findNextAction);
        findButtonPanel.add(findNextButton);

        findPreviousButton.setAction(findPrevAction);
        findButtonPanel.add(findPreviousButton);

        findCancelButton.setText("Cancel");
        findCancelButton.setActionCommand(SEARCH_CANCEL_COMMAND);
        findCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findCancelButtonActionPerformed(evt);
            }
        });
        findButtonPanel.add(findCancelButton);

        settingPanel.setLayout(new java.awt.GridLayout(3, 0, 0, 7));

        matchCaseOption.setText("Match Case");
        matchCaseOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchCaseOptionActionPerformed(evt);
            }
        });
        settingPanel.add(matchCaseOption);

        matchSpacesOption.setSelected(true);
        matchSpacesOption.setText("Match White Spaces");
        matchSpacesOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchSpacesOptionActionPerformed(evt);
            }
        });
        settingPanel.add(matchSpacesOption);

        findWrapOption.setSelected(true);
        findWrapOption.setText("Wrap Around");
        findWrapOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findWrapOptionActionPerformed(evt);
            }
        });
        settingPanel.add(findWrapOption);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(settingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(findButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(findButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(settingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void findCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findCancelButtonActionPerformed
        fireActionPerformed(evt);
    }//GEN-LAST:event_findCancelButtonActionPerformed

    private void matchSpacesOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchSpacesOptionActionPerformed
        updateFindActionsEnabled();
        firePropertyChange(MATCH_SPACES_PROPERTY_CHANGED,
                !matchSpacesOption.isSelected(),matchSpacesOption.isSelected());
    }//GEN-LAST:event_matchSpacesOptionActionPerformed

    private void matchCaseOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchCaseOptionActionPerformed
        firePropertyChange(MATCH_CASE_PROPERTY_CHANGED,
                !matchCaseOption.isSelected(),matchCaseOption.isSelected());
    }//GEN-LAST:event_matchCaseOptionActionPerformed

    private void findWrapOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findWrapOptionActionPerformed
        firePropertyChange(WRAP_AROUND_PROPERTY_CHANGED,
                !findWrapOption.isSelected(),findWrapOption.isSelected());
    }//GEN-LAST:event_findWrapOptionActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        if (findNextAction.isEnabled())
            findNextAction.actionPerformed(evt);
        else
            UIManager.getLookAndFeel().provideErrorFeedback(searchField);
//            Toolkit.getDefaultToolkit().beep();
    }//GEN-LAST:event_searchFieldActionPerformed

    @Override
    public void setEnabled(boolean enabled){
        super.setEnabled(enabled);
        findWrapOption.setEnabled(enabled);
        matchSpacesOption.setEnabled(enabled);
        matchCaseOption.setEnabled(enabled);
        updateFindActionsEnabled();
    }
    
    protected void updateFindActionsEnabled(){
        String searchText = getSearchText();
        boolean enabled = isEnabled() && searchText != null && !searchText.isEmpty();
        if (searchText != null && !getMatchSpaces())
            enabled &= !searchText.isBlank();
        findNextAction.setEnabled(enabled);
        findPrevAction.setEnabled(enabled);
    }
    
    public boolean getMatchSpaces(){
        return matchSpacesOption.isSelected();
    }
    
    public void setMatchSpaces(boolean value){
        matchSpacesOption.setSelected(value);
        firePropertyChange(MATCH_SPACES_PROPERTY_CHANGED,!value,value);
    }
    
    public boolean getMatchCase(){
        return matchCaseOption.isSelected();
    }
    
    public void setMatchCase(boolean value){
        matchCaseOption.setSelected(value);
        firePropertyChange(MATCH_CASE_PROPERTY_CHANGED,!value,value);
    }
    
    public boolean getWrapAround(){
        return findWrapOption.isSelected();
    }
    
    public void setWrapAround(boolean value){
        findWrapOption.setSelected(value);
        firePropertyChange(WRAP_AROUND_PROPERTY_CHANGED,!value,value);
    }
    
    public String getSearchText(){
        return searchField.getText();
    }
    
    public void setSearchText(String text){
        searchField.setText(text);
    }
    
    public JPopupMenu getSearchPopupMenu(){
        return searchField.getComponentPopupMenu();
    }
    
    public void setSearchPopupMenu(JPopupMenu popup){
        searchField.setComponentPopupMenu(popup);
    }
    
    public JTextField getSearchTextField(){
        return searchField;
    }
    
    protected void fireActionPerformed(ActionEvent evt){
        if (evt == null)
            return;
        else if (evt.getSource() != this)
            evt = new ActionEvent(this,evt.getID(),evt.getActionCommand(),
                    evt.getWhen(),evt.getModifiers());
        for (ActionListener l : getActionListeners()){
            if (l != null)
                l.actionPerformed(evt);
        }
    }
    
    /**
     * This adds the given {@code ActionListener} to this panel.
     * @param l The listener to add.
     * @see #removeActionListener(java.awt.event.ActionListener) 
     * @see #getActionListeners() 
     */
    public void addActionListener(ActionListener l){
        if (l != null)          // If the listener is not null
            listenerList.add(ActionListener.class, l);
    }
    /**
     * This removes the given {@code ActionListener} from this panel.
     * @param l The listener to remove.
     * @see #addActionListener(java.awt.event.ActionListener) 
     * @see #getActionListeners() 
     */
    public void removeActionListener(ActionListener l){
        listenerList.remove(ActionListener.class, l);
    }
    /**
     * This returns an array containing all the {@code ActionListener}s that 
     * have been added to this panel.
     * @return An array containing the {@code ActionListener}s that have been 
     * added, or an empty array if none have been added.
     * @see #addActionListener(java.awt.event.ActionListener) 
     * @see #removeActionListener(java.awt.event.ActionListener) 
     */
    public ActionListener[] getActionListeners(){
        return listenerList.getListeners(ActionListener.class);
    }
    
    public void addDocumentListener(DocumentListener l){
        if (l != null)
            listenerList.add(DocumentListener.class, l);
    }
    
    public void removeDocumentListener(DocumentListener l){
        listenerList.remove(DocumentListener.class, l);
    }
    
    public DocumentListener[] getDocumentListeners(){
        return listenerList.getListeners(DocumentListener.class);
    }
    
    public Action getFindNextAction(){
        return findNextAction;
    }
    
    public Action getFindPreviousAction(){
        return findPrevAction;
    }
    
    private final FindAction findNextAction;
    private final FindAction findPrevAction;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel findButtonPanel;
    private javax.swing.JButton findCancelButton;
    private javax.swing.JButton findNextButton;
    private javax.swing.JButton findPreviousButton;
    private javax.swing.JCheckBox findWrapOption;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox matchCaseOption;
    private javax.swing.JCheckBox matchSpacesOption;
    private javax.swing.JTextField searchField;
    private javax.swing.JPopupMenu searchPopupMenu;
    private javax.swing.JPanel settingPanel;
    // End of variables declaration//GEN-END:variables

    private class Handler implements DocumentListener{
        @Override
        public void insertUpdate(DocumentEvent e) {
            updateFindActionsEnabled();
            for (DocumentListener l : getDocumentListeners()){
                if (l != null)
                    l.insertUpdate(e);
            }
        }
        @Override
        public void removeUpdate(DocumentEvent e) {
            updateFindActionsEnabled();
            for (DocumentListener l : getDocumentListeners()){
                if (l != null)
                    l.removeUpdate(e);
            }
        }
        @Override
        public void changedUpdate(DocumentEvent e) {
            updateFindActionsEnabled();
            for (DocumentListener l : getDocumentListeners()){
                if (l != null)
                    l.changedUpdate(e);
            }
        }
    }
    
    protected class FindAction extends AbstractAction{
        
        private final Position.Bias direction;
        
        public FindAction(Position.Bias direction){
            super("Find "+((direction == Position.Bias.Backward) ? "Previous":"Next"));
            this.direction = Objects.requireNonNull(direction);
            int accMod = 0;
            if (direction == Position.Bias.Backward){
                accMod = InputEvent.SHIFT_DOWN_MASK;
                super.putValue(MNEMONIC_KEY, KeyEvent.VK_V);
                super.putValue(ACTION_COMMAND_KEY, SEARCH_FIND_PREVIOUS_COMMAND);
            }
            else if (direction == Position.Bias.Forward){
                super.putValue(MNEMONIC_KEY, KeyEvent.VK_X);
                super.putValue(ACTION_COMMAND_KEY, SEARCH_FIND_NEXT_COMMAND);
            }
            super.putValue(ACCELERATOR_KEY, KeyStroke.getKeyStroke(KeyEvent.VK_F3,
                    accMod));
        }
        
        public Position.Bias getDirection(){
            return direction;
        }
        @Override
        public void actionPerformed(ActionEvent evt) {
            fireActionPerformed(evt);
        }
    }
}
