/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manager;

import components.AbstractDialogPanel;
import static components.AbstractDialogPanel.ERROR_OPTION;
import java.awt.Component;
import java.util.Objects;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Mosblinker
 */
public class UpdateCheckPanel extends AbstractDialogPanel {
    /**
     * 
     */
    public static final String PROGRAM_NAME_PROPERTY_CHANGED = 
            "ProgramNamePropertyChanged";
    /**
     * 
     */
    public static final String PROGRAM_ICON_PROPERTY_CHANGED = 
            "ProgramIconPropertyChanged";
    /**
     * 
     */
    public static final String CURRENT_VERSION_PROPERTY_CHANGED = 
            "CurrentVersionPropertyChanged";
    /**
     * 
     */
    public static final String LATEST_VERSION_PROPERTY_CHANGED = 
            "LatestVersionPropertyChanged";
    /**
     * 
     */
    public static final String CHECK_FOR_UPDATES_AT_STARTUP_PROPERTY_CHANGED = 
            "CheckForUpdatesPropertyChanged";
    /**
     * 
     */
    public static final String OPEN_WEBSITE_COMMAND = "OpenWebsite";
    /**
     * 
     */
    public static final String CLOSE_DIALOG_COMMAND = "CloseDialog";
    /**
     * 
     */
    public static final int CLOSE_DIALOG_OPTION = 0;
    /**
     * 
     */
    protected static final String PROGRAM_UPDATE_TEXT_TEMPLATE = 
            "A new version of %s is available.";
    /**
     * Creates new form UpdateCheckPanel
     */
    public UpdateCheckPanel() {
        initComponents();
        updateProgramName();
        checkForUpdates = checkUpdatesAtStartToggle.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        updatePanel = new javax.swing.JPanel();
        updateIconLabel = new javax.swing.JLabel();
        updateTextLabel = new javax.swing.JLabel();
        currentVersTextLabel = new javax.swing.JLabel();
        latestVersTextLabel = new javax.swing.JLabel();
        checkUpdatesAtStartToggle = new javax.swing.JCheckBox();
        currentVersLabel = new javax.swing.JLabel();
        latestVersLabel = new javax.swing.JLabel();
        updateContinueButton = new javax.swing.JButton();
        updateOpenButton = new javax.swing.JButton();

        updatePanel.setLayout(new java.awt.GridBagLayout());

        updateIconLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        updateIconLabel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                updateIconLabelPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 18);
        updatePanel.add(updateIconLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 18, 0);
        updatePanel.add(updateTextLabel, gridBagConstraints);

        currentVersTextLabel.setText("Current Version:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 12);
        updatePanel.add(currentVersTextLabel, gridBagConstraints);

        latestVersTextLabel.setText("Latest Version:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 12);
        updatePanel.add(latestVersTextLabel, gridBagConstraints);

        checkUpdatesAtStartToggle.setSelected(true);
        checkUpdatesAtStartToggle.setText("Check for Updates at startup");
        checkUpdatesAtStartToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkUpdatesAtStartToggleActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 0, 0);
        updatePanel.add(checkUpdatesAtStartToggle, gridBagConstraints);

        currentVersLabel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                currentVersLabelPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        updatePanel.add(currentVersLabel, gridBagConstraints);

        latestVersLabel.setMaximumSize(new java.awt.Dimension(400, 196));
        latestVersLabel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                latestVersLabelPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        updatePanel.add(latestVersLabel, gridBagConstraints);

        updateContinueButton.setText("Continue");
        updateContinueButton.setActionCommand(CLOSE_DIALOG_COMMAND);
        updateContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateContinueButtonActionPerformed(evt);
            }
        });

        updateOpenButton.setText("Go to web page");
        updateOpenButton.setActionCommand(OPEN_WEBSITE_COMMAND);
        updateOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateOpenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(updateOpenButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateContinueButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateContinueButton)
                    .addComponent(updateOpenButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkUpdatesAtStartToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkUpdatesAtStartToggleActionPerformed
        setCheckForUpdatesAtStartup(checkUpdatesAtStartToggle.isSelected());
    }//GEN-LAST:event_checkUpdatesAtStartToggleActionPerformed

    private void updateContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateContinueButtonActionPerformed
        closeDialog(evt);
    }//GEN-LAST:event_updateContinueButtonActionPerformed

    private void updateOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateOpenButtonActionPerformed
        fireActionPerformed(evt);
    }//GEN-LAST:event_updateOpenButtonActionPerformed

    private void currentVersLabelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_currentVersLabelPropertyChange
        fireLabelPropertyChanged(evt,CURRENT_VERSION_PROPERTY_CHANGED);
    }//GEN-LAST:event_currentVersLabelPropertyChange

    private void latestVersLabelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_latestVersLabelPropertyChange
        fireLabelPropertyChanged(evt,LATEST_VERSION_PROPERTY_CHANGED);
    }//GEN-LAST:event_latestVersLabelPropertyChange

    private void updateIconLabelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_updateIconLabelPropertyChange
        fireLabelPropertyChanged(evt,PROGRAM_ICON_PROPERTY_CHANGED);
    }//GEN-LAST:event_updateIconLabelPropertyChange
    /**
     * 
     * @param evt
     * @param propName 
     */
    private void fireLabelPropertyChanged(java.beans.PropertyChangeEvent evt, 
            String propName){
        switch(evt.getPropertyName()){
            case ("text"):
            case ("icon"):
                firePropertyChange(propName,evt.getOldValue(),evt.getNewValue());
        }
    }
    /**
     * 
     * @param value 
     */
    public void setCheckForUpdatesAtStartup(boolean value){
        if (checkForUpdates != value){
            checkForUpdates = value;
            firePropertyChange(CHECK_FOR_UPDATES_AT_STARTUP_PROPERTY_CHANGED,
                    !value,value);
            checkUpdatesAtStartToggle.setSelected(value);
        }
    }
    /**
     * 
     * @return 
     */
    public boolean getCheckForUpdatesAtStartup(){
        return checkForUpdates;
    }
    /**
     * 
     */
    private void updateProgramName(){
        updateTextLabel.setText(String.format(PROGRAM_UPDATE_TEXT_TEMPLATE, 
                Objects.toString(programName,"the program")));
    }
    /**
     * 
     * @param name 
     */
    public void setProgramName(String name){
        if (!Objects.equals(name, programName)){
            String old = programName;
            programName = name;
            firePropertyChange(PROGRAM_NAME_PROPERTY_CHANGED,old,name);
            updateProgramName();
        }
    }
    /**
     * 
     * @return 
     */
    public String getProgramName(){
        return programName;
    }
    /**
     * 
     * @param icon 
     */
    public void setProgramIcon(Icon icon){
        updateIconLabel.setIcon(icon);
    }
    /**
     * 
     * @return 
     */
    public Icon getProgramIcon(){
        return updateIconLabel.getIcon();
    }
    /**
     * 
     * @param version 
     */
    public void setCurrentVersion(String version){
        currentVersLabel.setText(version);
    }
    /**
     * 
     * @return 
     */
    public String getCurrentVersion(){
        return currentVersLabel.getText();
    }
    /**
     * 
     * @param version 
     */
    public void setLatestVersion(String version){
        latestVersLabel.setText(version);
    }
    /**
     * 
     * @return 
     */
    public String getLatestVersion(){
        return latestVersLabel.getText();
    }
    @Override
    protected void setupDialog(JDialog dialog){
        dialog.setResizable(false);
    }
    @Override
    protected String getDialogClosingCommand() {
        return CLOSE_DIALOG_COMMAND;
    }
    @Override
    protected int getOptionForCommand(String command) {
        if (command != null){           // If the command is not null
            switch(command){
                case(CLOSE_DIALOG_COMMAND):  // If the command is the close command
                    return CLOSE_DIALOG_OPTION;
            }
        }
        return ERROR_OPTION;
    }
    /**
     * {@inheritDoc }
     * @param option {@inheritDoc }
     * @return {@inheritDoc }
     * @see #getOption() 
     * @see #getOptionForCommand(String) 
     */
    @Override
    protected String getOptionString(int option) {
        switch(option){
            case(CLOSE_DIALOG_OPTION):            // If this is the close option
                return "CLOSE_DIALOG_OPTION";
            default:
                return null;
        }
    }
    /**
     * 
     * @param enabled 
     */
    @Override
    public void setEnabled(boolean enabled){
        super.setEnabled(enabled);
        if (updateOpenButton != null)
            updateOpenButton.setEnabled(enabled);
    }
    /**
     * 
     * @param parent 
     */
    public void showUpToDateDialog(Component parent){
        JOptionPane.showMessageDialog(parent, 
                "This program is already up to date,",
                getDialogTitle(), JOptionPane.INFORMATION_MESSAGE, 
                getProgramIcon());
    }
    @Override
    protected String paramString(){
        return super.paramString() + 
                ",programName="+Objects.toString(getProgramName(), "")+
                ",currentVersion="+Objects.toString(getCurrentVersion(),"")+
                ",latestVersion="+Objects.toString(getLatestVersion(), "")+
                ",programIcon="+Objects.toString(getProgramIcon(), "")+
                ((getCheckForUpdatesAtStartup()) ? ",checksForUpdatesAtStartup":"");
    }
    /**
     * 
     */
    private String programName = null;
    /**
     * 
     */
    private boolean checkForUpdates;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkUpdatesAtStartToggle;
    private javax.swing.JLabel currentVersLabel;
    private javax.swing.JLabel currentVersTextLabel;
    private javax.swing.JLabel latestVersLabel;
    private javax.swing.JLabel latestVersTextLabel;
    private javax.swing.JButton updateContinueButton;
    private javax.swing.JLabel updateIconLabel;
    private javax.swing.JButton updateOpenButton;
    private javax.swing.JPanel updatePanel;
    private javax.swing.JLabel updateTextLabel;
    // End of variables declaration//GEN-END:variables
}
