/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package manager.links;

import components.*;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.FileReader;
import java.io.IOException;
import java.util.*;
import javax.swing.AbstractButton;
import javax.swing.event.*;
import javax.swing.text.Position;

/**
 *
 * @author Milo Steier
 */
public class LinksListModelTester extends javax.swing.JFrame {
    
    private static final String TEST_LINKS_FILE = 
            "C:\\Users\\Milo Steier\\OneDrive\\Documents\\Programs\\Java\\My Programs\\LinkManager\\Development Stuff\\Testing.txt";

    /**
     * Creates new form SetOfLinksModelTester
     */
    public LinksListModelTester() {
        model = new LinksListModel();
        Handler handler = new Handler();
        model.addChangeListener(handler);
        model.addPropertyChangeListener(handler);
        model.addListDataListener(handler);
        model.addListSelectionListener(handler);
        initComponents();
        editedToggle.setSelected(model.isEdited());
        String[] defaultValues = {"Hello","Test","Hi"};
        model.addAll(Arrays.asList(defaultValues));
        for (int i = 0; i < 20; i++)
            model.add("Test " + i);
//        model.setLinkID("Hi", null);
        tabbedPane.setTabComponentAt(tabbedPane.indexOfComponent(jPanel2), jLabel3);
        modLimitToggle.setSelected(model.isModificationLimitEnabled());
        createdSpinner.setValue(model.getCreationTime());
        lastModSpinner.setValue(model.getLastModified());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listManipulator = new components.JListManipulator<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        linkField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        manageButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        listIDSpinner = new javax.swing.JSpinner();
        editedToggle = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        clearEditedButton = new javax.swing.JButton();
        lastModSpinner = new javax.swing.JSpinner();
        clearNameButton = new javax.swing.JButton();
        setNameButton = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        setLastModButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        modContentsDisplay = new javax.swing.JCheckBox();
        sizeLimitToggle = new javax.swing.JCheckBox();
        sizeLimitSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        createdSpinner = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        listDataListenerToggle = new javax.swing.JCheckBoxMenuItem();
        changeListenerToggle = new javax.swing.JCheckBoxMenuItem();
        propChangeListenerToggle = new javax.swing.JCheckBoxMenuItem();
        listSelListenerToggle = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        matchCaseToggle = new javax.swing.JCheckBoxMenuItem();
        matchSpacesToggle = new javax.swing.JCheckBoxMenuItem();
        wrapAroundToggle = new javax.swing.JCheckBoxMenuItem();
        findNextButton = new javax.swing.JMenuItem();
        findPrevButton = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        allowDupToggle = new javax.swing.JCheckBoxMenuItem();
        readOnlyToggle = new javax.swing.JCheckBoxMenuItem();
        flag04Toggle = new javax.swing.JCheckBoxMenuItem();
        flag08Toggle = new javax.swing.JCheckBoxMenuItem();
        flag10Toggle = new javax.swing.JCheckBoxMenuItem();
        flag20Toggle = new javax.swing.JCheckBoxMenuItem();
        flag40Toggle = new javax.swing.JCheckBoxMenuItem();
        flag80Toggle = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        removeDupItem = new javax.swing.JMenuItem();
        setLastModCurrItem = new javax.swing.JMenuItem();
        modContentsItem = new javax.swing.JMenuItem();
        modLimitToggle = new javax.swing.JCheckBoxMenuItem();
        addAllFileItem = new javax.swing.JMenuItem();
        addFileItem = new javax.swing.JMenuItem();

        listManipulator.setResetButtonIsShown(false);
        listManipulator.setSideAccessory(jPanel1);

        jLabel3.setText("jLabel3");
        jLabel3.setToolTipText("Hello");

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jButton1.setText("Randomize");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        list.setModel(model);
        list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list.setToolTipText(model.getToolTipText());
        list.setSelectionModel(model);
        list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list);

        tabbedPane.addTab("Model", jScrollPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        tabbedPane.addTab("tab3", null, jPanel2, "Hello There");

        linkField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.setEnabled(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        manageButton.setText("Manage");
        manageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageButtonActionPerformed(evt);
            }
        });

        printButton.setText("Print Data");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        listIDSpinner.setModel(new javax.swing.SpinnerNumberModel());
        listIDSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                listIDSpinnerStateChanged(evt);
            }
        });

        editedToggle.setText("Is Edited");
        editedToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editedToggleActionPerformed(evt);
            }
        });

        jLabel2.setText("lastMod:");

        clearEditedButton.setText("Clear Edited");
        clearEditedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearEditedButtonActionPerformed(evt);
            }
        });

        lastModSpinner.setModel(new javax.swing.SpinnerNumberModel(0L, null, null, 1L));

        clearNameButton.setText("Clear Name");
        clearNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearNameButtonActionPerformed(evt);
            }
        });

        setNameButton.setText("Set Name");
        setNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setNameButtonActionPerformed(evt);
            }
        });

        setLastModButton.setText("Set LastMod");
        setLastModButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLastModButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("ListID:");

        modContentsDisplay.setText("Contents Modified");
        modContentsDisplay.setEnabled(false);

        sizeLimitToggle.setText("Size Limit:");
        sizeLimitToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeLimitToggleActionPerformed(evt);
            }
        });

        sizeLimitSpinner.setModel(new javax.swing.SpinnerNumberModel(100, null, null, 1));
        sizeLimitSpinner.setEnabled(false);
        sizeLimitSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sizeLimitSpinnerStateChanged(evt);
            }
        });

        jLabel4.setText("Created:");

        createdSpinner.setModel(new javax.swing.SpinnerNumberModel(0L, null, null, 1L));
        createdSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                createdSpinnerStateChanged(evt);
            }
        });

        jMenu1.setText("Listeners");

        listDataListenerToggle.setSelected(true);
        listDataListenerToggle.setText("ListDataListeners");
        jMenu1.add(listDataListenerToggle);

        changeListenerToggle.setSelected(true);
        changeListenerToggle.setText("ChangeListeners");
        jMenu1.add(changeListenerToggle);

        propChangeListenerToggle.setSelected(true);
        propChangeListenerToggle.setText("PropertyChangeListeners");
        jMenu1.add(propChangeListenerToggle);

        listSelListenerToggle.setSelected(true);
        listSelListenerToggle.setText("ListSelectionListeners");
        jMenu1.add(listSelListenerToggle);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Find");

        matchCaseToggle.setText("Match Case");
        jMenu2.add(matchCaseToggle);

        matchSpacesToggle.setSelected(true);
        matchSpacesToggle.setText("Match White Space");
        jMenu2.add(matchSpacesToggle);

        wrapAroundToggle.setSelected(true);
        wrapAroundToggle.setText("Wrap Around");
        jMenu2.add(wrapAroundToggle);

        findNextButton.setText("Find Next");
        findNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findNextButtonActionPerformed(evt);
            }
        });
        jMenu2.add(findNextButton);

        findPrevButton.setText("Find Previous");
        findPrevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findPrevButtonActionPerformed(evt);
            }
        });
        jMenu2.add(findPrevButton);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Flags");

        allowDupToggle.setText("Allows Duplicates");
        allowDupToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allowDupToggleActionPerformed(evt);
            }
        });
        jMenu4.add(allowDupToggle);

        readOnlyToggle.setText("Read Only");
        readOnlyToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readOnlyToggleActionPerformed(evt);
            }
        });
        jMenu4.add(readOnlyToggle);

        flag04Toggle.setText("Flag 0x04");
        flag04Toggle.setActionCommand("4");
        flag04Toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flagToggleActionPerformed(evt);
            }
        });
        jMenu4.add(flag04Toggle);

        flag08Toggle.setText("Flag 0x08");
        flag08Toggle.setActionCommand("8");
        flag08Toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flagToggleActionPerformed(evt);
            }
        });
        jMenu4.add(flag08Toggle);

        flag10Toggle.setText("Flag 0x10");
        flag10Toggle.setActionCommand("10");
        flag10Toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flagToggleActionPerformed(evt);
            }
        });
        jMenu4.add(flag10Toggle);

        flag20Toggle.setText("Flag 0x20");
        flag20Toggle.setActionCommand("20");
        flag20Toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flagToggleActionPerformed(evt);
            }
        });
        jMenu4.add(flag20Toggle);

        flag40Toggle.setText("Flag 0x40");
        flag40Toggle.setActionCommand("40");
        flag40Toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flagToggleActionPerformed(evt);
            }
        });
        jMenu4.add(flag40Toggle);

        flag80Toggle.setText("Flag 0x80");
        flag80Toggle.setActionCommand("80");
        flag80Toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flagToggleActionPerformed(evt);
            }
        });
        jMenu4.add(flag80Toggle);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Other Stuff");

        removeDupItem.setText("Remove Duplicates");
        removeDupItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDupButtonActionPerformed(evt);
            }
        });
        jMenu3.add(removeDupItem);

        setLastModCurrItem.setText("Set LastMod to Current");
        setLastModCurrItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLastModCurrButtonActionPerformed(evt);
            }
        });
        jMenu3.add(setLastModCurrItem);

        modContentsItem.setText("Modify Contents");
        modContentsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modContentsButtonActionPerformed(evt);
            }
        });
        jMenu3.add(modContentsItem);

        modLimitToggle.setText("Enable Modification Limits");
        modLimitToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modLimitToggleActionPerformed(evt);
            }
        });
        jMenu3.add(modLimitToggle);

        addAllFileItem.setText("Add From File (addAll)");
        addAllFileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAllFileItemActionPerformed(evt);
            }
        });
        jMenu3.add(addAllFileItem);

        addFileItem.setText("Add From File (add)");
        addFileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFileItemActionPerformed(evt);
            }
        });
        jMenu3.add(addFileItem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabbedPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sizeLimitToggle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sizeLimitSpinner)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createdSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nameField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setNameButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearNameButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editedToggle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearEditedButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastModSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setLastModButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modContentsDisplay)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(linkField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listIDSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(listIDSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(linkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(editButton)
                    .addComponent(manageButton)
                    .addComponent(printButton)
                    .addComponent(sizeLimitToggle)
                    .addComponent(sizeLimitSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(createdSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editedToggle)
                    .addComponent(jLabel2)
                    .addComponent(clearEditedButton)
                    .addComponent(lastModSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setLastModButton)
                    .addComponent(modContentsDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearNameButton)
                    .addComponent(setNameButton)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String text = linkField.getText();
        try{
            model.add(text);
            linkField.setText("");
        }
        catch(Exception ex){
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_addButtonActionPerformed
    
    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        if (list.isSelectionEmpty())
            return;
        String text = linkField.getText();
        try{
            System.out.println("Old Value: "+model.set(list.getSelectedIndex(), text));
            linkField.setText("");
        }
        catch(Exception ex){
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void manageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageButtonActionPerformed
        listManipulator.setListData(model);
        if (listManipulator.showDialog(this) == JListManipulator.ACCEPT_OPTION){
            List<String> values = listManipulator.getListData();
            long time = System.currentTimeMillis();
            try{
                model.setContents(values);
            }catch(Exception ex){
                System.out.println("Error: " + ex);
            }
            System.out.println("Time Taken: " + (System.currentTimeMillis()-time));
        }
    }//GEN-LAST:event_manageButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        System.out.println("Model: " + model);
        System.out.println("Set: " + model.set);
        System.out.println("Model and Set are Synced: " + model.containsAll(model.set) + " " + model.set.containsAll(model));
        System.out.println("ListID: " + model.getListID());
        System.out.println("List Name: " + model.getListName());
        System.out.println("Flags: " + model.getFlags());
        System.out.println("Allows Duplicates: " + model.getAllowsDuplicates());
        System.out.println("Is Read Only: " + model.isReadOnly());
        System.out.println("Modification Limit: " + model.isModificationLimitEnabled());
        System.out.println("Size Limit: " + model.getSizeLimit());
        System.out.println("Is Full: " + model.isFull());
        System.out.println("Is Edited: " + model.isEdited());
        System.out.println("Old ListID: " + model.oldListID+
                " (Changed: " + !Objects.equals(model.getListID(), model.oldListID)+")");
        System.out.println("Old List Name: " + model.oldName+
                " (Changed: " + !Objects.equals(model.getListName(), model.oldName)+")");
        System.out.println("\tOld Flags: " + model.oldFlags + 
                " (Changed: " + (model.getFlags() != model.oldFlags)+")");
        System.out.println("Old Size Limit: " + model.oldSizeLimit+
                " (Changed: " + !Objects.equals(model.getSizeLimit(), model.oldSizeLimit)+")");
        System.out.println("Contents Modified: " + model.getContentsModified());
        System.out.println("Last Modified: " + model.getLastModified());
        System.out.println("Created: " + model.getCreationTime());
        System.out.println("Tool Tip: " + model.getToolTipText());
        System.out.println("Hash Code: " + model.hashCode());
        
        System.out.println("Selected Indexes: " + Arrays.toString(model.getSelectedIndices()));
        System.out.println("Anchor Index: " + model.getAnchorSelectionIndex());
        System.out.println("Lead Index: " + model.getLeadSelectionIndex());
        
        System.out.println("Lowest Flag Set: " + Integer.lowestOneBit(model.getFlags()));
        System.out.println("Highest Flag Set: " + Integer.highestOneBit(model.getFlags()));
        System.out.println("Binary Flags: " + Integer.toBinaryString(model.getFlags()));
        System.out.println(LinksListModel.FLAG_PROPERTY_NAMES_MAP.keySet());
        
//        System.out.println();
//        ArrayList<String> test = new ArrayList<>();
//        for (int i = 0; i < 20; i++)
//            test.add("Item "+i);
//        System.out.println(test);
//        ArrayList<String> test2 = new ArrayList<>();
//        for (int i = 6; i <= 16; i+= 2)
//            test2.add("Item "+i);
//        System.out.println(test2);
//        List<String> test3 = test.subList(0, 11);
//        System.out.println(test3);
//        System.out.println(test3.size());
//        test3.removeAll(test2);
//        System.out.println(test);
//        System.out.println(test3);
//        System.out.println(test3.size());
//        test3.remove(4);
//        System.out.println(test);
//        System.out.println(test3);
//        System.out.println(test3.size());
//        test3.remove("Item 2");
//        System.out.println(test);
//        System.out.println(test3);
//        System.out.println(test3.size());
    }//GEN-LAST:event_printButtonActionPerformed

    private void listIDSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_listIDSpinnerStateChanged
        model.setListID((int)listIDSpinner.getValue());
    }//GEN-LAST:event_listIDSpinnerStateChanged

    private void editedToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editedToggleActionPerformed
        model.setEdited(editedToggle.isSelected());
    }//GEN-LAST:event_editedToggleActionPerformed

    private void clearEditedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearEditedButtonActionPerformed
        model.clearEdited();
    }//GEN-LAST:event_clearEditedButtonActionPerformed

    private void clearNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearNameButtonActionPerformed
        model.setListName(null);
    }//GEN-LAST:event_clearNameButtonActionPerformed

    private void setNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setNameButtonActionPerformed
        model.setListName(nameField.getText());
    }//GEN-LAST:event_setNameButtonActionPerformed

    private void removeDupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDupButtonActionPerformed
        System.out.println(model.removeDuplicates());
    }//GEN-LAST:event_removeDupButtonActionPerformed

    private void setLastModButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLastModButtonActionPerformed
        model.setLastModified((long)lastModSpinner.getValue());
    }//GEN-LAST:event_setLastModButtonActionPerformed

    private void setLastModCurrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLastModCurrButtonActionPerformed
        model.setLastModified();
        lastModSpinner.setValue(model.getLastModified());
    }//GEN-LAST:event_setLastModCurrButtonActionPerformed

    private void listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listValueChanged
        editButton.setEnabled(list.getSelectedIndices().length == 1);
    }//GEN-LAST:event_listValueChanged

    private void findNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findNextButtonActionPerformed
        findActionPerformed(Position.Bias.Forward);
    }//GEN-LAST:event_findNextButtonActionPerformed

    private void findPrevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findPrevButtonActionPerformed
        findActionPerformed(Position.Bias.Backward);
    }//GEN-LAST:event_findPrevButtonActionPerformed

    private void modContentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modContentsButtonActionPerformed
        model.setContentsModified();
    }//GEN-LAST:event_modContentsButtonActionPerformed

    private void allowDupToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allowDupToggleActionPerformed
        model.setAllowsDuplicates(allowDupToggle.isSelected());
    }//GEN-LAST:event_allowDupToggleActionPerformed

    private void readOnlyToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readOnlyToggleActionPerformed
        model.setReadOnly(readOnlyToggle.isSelected());
    }//GEN-LAST:event_readOnlyToggleActionPerformed

    private void flagToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flagToggleActionPerformed
        if (!(evt.getSource() instanceof AbstractButton))
            return;
        try{
            model.setFlag(Integer.parseInt(evt.getActionCommand(), 16), 
                    ((AbstractButton)evt.getSource()).isSelected());
        } catch(NumberFormatException ex){
            System.out.println("0x"+evt.getActionCommand()+" Is not a valid flag");
        }
    }//GEN-LAST:event_flagToggleActionPerformed

    private void sizeLimitToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeLimitToggleActionPerformed
        sizeLimitSpinner.setEnabled(sizeLimitToggle.isSelected());
        model.setSizeLimit((sizeLimitToggle.isSelected())?(Integer)sizeLimitSpinner.getValue():null);
    }//GEN-LAST:event_sizeLimitToggleActionPerformed

    private void sizeLimitSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sizeLimitSpinnerStateChanged
        if (sizeLimitSpinner.isEnabled()){
            Integer value = (Integer)sizeLimitSpinner.getValue();
            if (!Objects.equals(value, model.getSizeLimit()))
                model.setSizeLimit(value);
        }
    }//GEN-LAST:event_sizeLimitSpinnerStateChanged

    private void modLimitToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modLimitToggleActionPerformed
        model.setModificationLimitEnabled(modLimitToggle.isSelected());
    }//GEN-LAST:event_modLimitToggleActionPerformed

    private void createdSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_createdSpinnerStateChanged
        model.setCreationTime((Long)createdSpinner.getValue());
    }//GEN-LAST:event_createdSpinnerStateChanged
    
    private void addFromFile(boolean useAddAll){
        try(FileReader reader = new FileReader(TEST_LINKS_FILE);
                Scanner scanner = new Scanner(reader)){
            List<String> list;
            if (useAddAll)
                list = new ArrayList<>();
            else
                list = model;
            while(scanner.hasNextLine())
                list.add(scanner.nextLine());
            if (useAddAll)
                model.addAll(list);
        } catch (IOException ex) {
            System.out.println("Error: " +ex);
        }
    }
    
    private void addAllFileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAllFileItemActionPerformed
        addFromFile(true);
    }//GEN-LAST:event_addAllFileItemActionPerformed

    private void addFileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFileItemActionPerformed
        addFromFile(false);
    }//GEN-LAST:event_addFileItemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Collections.shuffle(listManipulator.getModelList());
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void findActionPerformed(Position.Bias dir){
        int sel = Math.max(list.getSelectedIndex(), 0);
        int index = model.getNextMatch(linkField.getText(), sel, dir, 
                matchSpacesToggle.isSelected(), 
                matchCaseToggle.isSelected(), 
                wrapAroundToggle.isSelected());
        System.out.println("Found Index: " + index);
        list.setSelectedIndex(index);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LinksListModelTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LinksListModelTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LinksListModelTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LinksListModelTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LinksListModelTester().setVisible(true);
            }
        });
    }
    
    private LinksListModel model;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addAllFileItem;
    private javax.swing.JButton addButton;
    private javax.swing.JMenuItem addFileItem;
    private javax.swing.JCheckBoxMenuItem allowDupToggle;
    private javax.swing.JCheckBoxMenuItem changeListenerToggle;
    private javax.swing.JButton clearEditedButton;
    private javax.swing.JButton clearNameButton;
    private javax.swing.JSpinner createdSpinner;
    private javax.swing.JButton editButton;
    private javax.swing.JCheckBox editedToggle;
    private javax.swing.JMenuItem findNextButton;
    private javax.swing.JMenuItem findPrevButton;
    private javax.swing.JCheckBoxMenuItem flag04Toggle;
    private javax.swing.JCheckBoxMenuItem flag08Toggle;
    private javax.swing.JCheckBoxMenuItem flag10Toggle;
    private javax.swing.JCheckBoxMenuItem flag20Toggle;
    private javax.swing.JCheckBoxMenuItem flag40Toggle;
    private javax.swing.JCheckBoxMenuItem flag80Toggle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner lastModSpinner;
    private javax.swing.JTextField linkField;
    private javax.swing.JList<String> list;
    private javax.swing.JCheckBoxMenuItem listDataListenerToggle;
    private javax.swing.JSpinner listIDSpinner;
    private components.JListManipulator<String> listManipulator;
    private javax.swing.JCheckBoxMenuItem listSelListenerToggle;
    private javax.swing.JButton manageButton;
    private javax.swing.JCheckBoxMenuItem matchCaseToggle;
    private javax.swing.JCheckBoxMenuItem matchSpacesToggle;
    private javax.swing.JCheckBox modContentsDisplay;
    private javax.swing.JMenuItem modContentsItem;
    private javax.swing.JCheckBoxMenuItem modLimitToggle;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton printButton;
    private javax.swing.JCheckBoxMenuItem propChangeListenerToggle;
    private javax.swing.JCheckBoxMenuItem readOnlyToggle;
    private javax.swing.JMenuItem removeDupItem;
    private javax.swing.JButton setLastModButton;
    private javax.swing.JMenuItem setLastModCurrItem;
    private javax.swing.JButton setNameButton;
    private javax.swing.JSpinner sizeLimitSpinner;
    private javax.swing.JCheckBox sizeLimitToggle;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JCheckBoxMenuItem wrapAroundToggle;
    // End of variables declaration//GEN-END:variables

    private class Handler implements ListDataListener, ChangeListener, PropertyChangeListener, ListSelectionListener{

        @Override
        public void intervalAdded(ListDataEvent evt) {
            if (listDataListenerToggle.isSelected())
                System.out.println("IntervalAdded: " + evt);
            list.setToolTipText(model.getToolTipText());
        }

        @Override
        public void intervalRemoved(ListDataEvent evt) {
            if (listDataListenerToggle.isSelected())
                System.out.println("IntervalRemoved: " + evt);
            list.setToolTipText(model.getToolTipText());
        }

        @Override
        public void contentsChanged(ListDataEvent evt) {
            if (listDataListenerToggle.isSelected())
                System.out.println("ContentsChanged: " + evt);
            list.setToolTipText(model.getToolTipText());
        }

        @Override
        public void stateChanged(ChangeEvent evt) {
            if (changeListenerToggle.isSelected())
                System.out.println("StateChanged: " + evt);
            editedToggle.setSelected(model.isEdited());
            modContentsDisplay.setSelected(model.getContentsModified());
        }

        @Override
        public void propertyChange(PropertyChangeEvent evt) {
            if (propChangeListenerToggle.isSelected())
                System.out.println("PropertyChanged: " +evt);
        }

        @Override
        public void valueChanged(ListSelectionEvent evt) {
            if (listSelListenerToggle.isSelected())
                System.out.println("ListSelection: " +evt);
        }
        
    }
}
