/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manager.database;

import java.awt.Component;
import java.awt.event.*;
import java.sql.*;
import java.util.Objects;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.table.*;
import manager.*;
import sql.UncheckedSQLException;

/**
 *
 * @author Mosblinker
 */
public class DatabaseQueryTestPanel extends JPanel {
    /**
     * 
     */
    public static final String DATABASE_QUERY_EXECUTE_COMMAND = "ExecuteQuery";
    /**
     * 
     */
    public static final String EXECUTION_TIME_PROPERTY_CHANGED = 
            "TimePropertyChanged";
    /**
     * 
     */
    public static final int BLANK_SHOWN_STATE = 0;
    /**
     * 
     */
    public static final int RESULTS_SHOWN_STATE = 1;
    /**
     * 
     */
    public static final int UPDATES_SHOWN_STATE = 2;
    /**
     * 
     */
    public static final int ERROR_SHOWN_STATE = 3;
    /**
     * Creates new form DatabaseQueryTestPanel
     */
    public DatabaseQueryTestPanel() {
        initComponents();
        dbQueryField.getDocument().addDocumentListener(new Handler());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        popupMenu = new javax.swing.JPopupMenu();
        dbQueryField = new javax.swing.JTextField();
        javax.swing.JLabel dbQueryLabel = new javax.swing.JLabel();
        executeQueryButton = new javax.swing.JButton();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        dbQueryTimeLabel = new javax.swing.JLabel();
        dbQueryResultsPanel = new javax.swing.JPanel();
        dbQueryBlankCard = new javax.swing.JLabel();
        dbQueryScrollPane = new javax.swing.JScrollPane();
        dbQueryTable = new javax.swing.JTable();
        dbQueryUpdatePanel = new javax.swing.JPanel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        dbQueryUpdateLabel = new javax.swing.JLabel();
        dbQueryErrorPanel = new javax.swing.JPanel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        dbQueryErrorLabel = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        dbQueryErrorCodeLabel = new javax.swing.JLabel();

        dbQueryField.setComponentPopupMenu(popupMenu);
        dbQueryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeQueryActionPerformed(evt);
            }
        });

        dbQueryLabel.setText("Query:");

        executeQueryButton.setText("Execute");
        executeQueryButton.setEnabled(false);
        executeQueryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeQueryActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Results"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("Time:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        dbQueryTimeLabel.setText("0 ms");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 6, 0, 12);
        jPanel1.add(dbQueryTimeLabel, gridBagConstraints);

        dbQueryResultsPanel.setLayout(new java.awt.CardLayout());

        dbQueryBlankCard.setName("blank"); // NOI18N
        dbQueryResultsPanel.add(dbQueryBlankCard, "blank");

        dbQueryScrollPane.setName("table"); // NOI18N

        dbQueryTable.setAutoCreateRowSorter(true);
        dbQueryScrollPane.setViewportView(dbQueryTable);

        dbQueryResultsPanel.add(dbQueryScrollPane, "table");

        dbQueryUpdatePanel.setName("update"); // NOI18N

        jLabel3.setText("Update Count: ");

        dbQueryUpdateLabel.setText("-1");

        javax.swing.GroupLayout dbQueryUpdatePanelLayout = new javax.swing.GroupLayout(dbQueryUpdatePanel);
        dbQueryUpdatePanel.setLayout(dbQueryUpdatePanelLayout);
        dbQueryUpdatePanelLayout.setHorizontalGroup(
            dbQueryUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbQueryUpdatePanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dbQueryUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dbQueryUpdatePanelLayout.setVerticalGroup(
            dbQueryUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbQueryUpdatePanelLayout.createSequentialGroup()
                .addGroup(dbQueryUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dbQueryUpdateLabel))
                .addGap(0, 177, Short.MAX_VALUE))
        );

        dbQueryResultsPanel.add(dbQueryUpdatePanel, "update");

        dbQueryErrorPanel.setName("error"); // NOI18N

        jLabel6.setText("Error:");

        dbQueryErrorLabel.setText("N/A");

        jLabel10.setText("Error Code:");

        dbQueryErrorCodeLabel.setText("-1");

        javax.swing.GroupLayout dbQueryErrorPanelLayout = new javax.swing.GroupLayout(dbQueryErrorPanel);
        dbQueryErrorPanel.setLayout(dbQueryErrorPanelLayout);
        dbQueryErrorPanelLayout.setHorizontalGroup(
            dbQueryErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbQueryErrorPanelLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dbQueryErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dbQueryErrorPanelLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dbQueryErrorCodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
        );
        dbQueryErrorPanelLayout.setVerticalGroup(
            dbQueryErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbQueryErrorPanelLayout.createSequentialGroup()
                .addGroup(dbQueryErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dbQueryErrorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dbQueryErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(dbQueryErrorCodeLabel))
                .addGap(0, 154, Short.MAX_VALUE))
        );

        dbQueryResultsPanel.add(dbQueryErrorPanel, "error");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.weighty = 0.9;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 13, 12);
        jPanel1.add(dbQueryResultsPanel, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dbQueryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dbQueryField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(executeQueryButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(executeQueryButton)
                    .addComponent(dbQueryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbQueryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * 
     * @param evt 
     */
    private void executeQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeQueryActionPerformed
            // If the execute query button is disabled
        if (!executeQueryButton.isEnabled())
            UIManager.getLookAndFeel().provideErrorFeedback(dbQueryField);
        else
            fireActionPerformed(evt.getID(),DATABASE_QUERY_EXECUTE_COMMAND,
                    evt.getWhen(),evt.getModifiers());
    }//GEN-LAST:event_executeQueryActionPerformed
    /**
     * 
     * @return 
     */
    public JTextField getQueryTextField(){
        return dbQueryField;
    }
    /**
     * 
     * @return 
     */
    public JPopupMenu getQueryPopupMenu(){
        return popupMenu;
    }
    /**
     * 
     * @return 
     */
    public JButton getQueryExecuteButton(){
        return executeQueryButton;
    }
    /**
     * 
     * @return 
     */
    public JScrollPane getResultsScrollPane(){
        return dbQueryScrollPane;
    }
    /**
     * 
     * @return 
     */
    public JTable getResultsTable(){
        return dbQueryTable;
    }
    /**
     * 
     * @return 
     */
    public String getQuery(){
        return dbQueryField.getText();
    }
    /**
     * 
     * @param query 
     */
    public void setQuery(String query){
        dbQueryField.setText(query);
    }
    /**
     * 
     * @return 
     */
    public long getExecutionTime(){
        return time;
    }
    /**
     * 
     * @param time 
     */
    public void setExecutionTime(long time){
        if (time != this.time){
            long old = this.time;
            this.time = time;
            firePropertyChange(EXECUTION_TIME_PROPERTY_CHANGED,old,time);
                // Set the label to display the time
            dbQueryTimeLabel.setText(time + " ms");
        }
    }
    /**
     * 
     * @param card 
     */
    protected void setResultsCard(Component card){
        LinkManagerUtilities.setCard(dbQueryResultsPanel, card.getName());
        fireStateChanged();
    }
    /**
     * 
     * @param model
     * @param updates
     * @param ex
     */
    protected void setResultsData(TableModel model, Integer updates, 
            Exception ex){
        resultsModel = model;
        updateCount = updates;
        this.ex = ex;
        if (ex instanceof SQLException)
            errorCode = ((SQLException)ex).getErrorCode();
        else if (ex instanceof UncheckedSQLException)
            errorCode = ((UncheckedSQLException)ex).getErrorCode();
        else
            errorCode = null;
    }
    /**
     * 
     */
    public void showBlank(){
        setResultsData(null,null,null);
        setResultsCard(dbQueryBlankCard);
    }
    /**
     * 
     * @param model 
     */
    public void showResults(TableModel model){
        setResultsData(model,null,null);
        dbQueryTable.setModel(model);
        setResultsCard(dbQueryScrollPane);
    }
    /**
     * 
     * @param resultSet
     * @throws java.sql.SQLException
     */
    public void showResults(ResultSet resultSet) throws SQLException{
        showResults(LinkDatabaseConnection.getTableModelForResultSet(resultSet));
    }
    /**
     * 
     * @param updateCount 
     */
    public void showUpdates(int updateCount){
        setResultsData(null,updateCount,null);
        dbQueryUpdateLabel.setText(""+updateCount);
        setResultsCard(dbQueryUpdatePanel);
    }
    /**
     * 
     * @param ex 
     */
    public void showError(Exception ex){
        setResultsData(null,null,ex);
        dbQueryErrorLabel.setText(Objects.toString(ex,"N/A"));
        dbQueryErrorCodeLabel.setText(Objects.toString(errorCode,"N/A"));
        setResultsCard(dbQueryErrorPanel);
    }
    /**
     * 
     * @return 
     */
    public TableModel getResultsModel(){
        return resultsModel;
    }
    /**
     * 
     * @return 
     */
    public Integer getUpdateCount(){
        return updateCount;
    }
    /**
     * 
     * @return 
     */
    public Exception getException(){
        return ex;
    }
    /**
     * 
     * @return 
     */
    public Integer getErrorCode(){
        return errorCode;
    }
    /**
     * 
     * @return 
     */
    public int getState(){
        if (resultsModel != null)
            return RESULTS_SHOWN_STATE;
        else if (updateCount != null)
            return UPDATES_SHOWN_STATE;
        else if (ex != null)
            return ERROR_SHOWN_STATE;
        return BLANK_SHOWN_STATE;
    }
    /**
     * This adds the given {@code ActionListener} to this panel.
     * @param l The listener to add.
     * @see #removeActionListener(java.awt.event.ActionListener) 
     * @see #getActionListeners() 
     */
    public void addActionListener(ActionListener l){
            // If the listener is not null
        if (l != null)
            listenerList.add(ActionListener.class, l);
    }
    /**
     * This removes the given {@code ActionListener} from this panel.
     * @param l The listener to remove.
     * @see #addActionListener(java.awt.event.ActionListener) 
     * @see #getActionListeners() 
     */
    public void removeActionListener(ActionListener l){
        listenerList.remove(ActionListener.class, l);
    }
    /**
     * This returns an array containing all the {@code ActionListener}s that 
     * have been added to this panel.
     * @return An array containing the {@code ActionListener}s that have been 
     * added, or an empty array if none have been added.
     * @see #addActionListener(java.awt.event.ActionListener) 
     * @see #removeActionListener(java.awt.event.ActionListener) 
     */
    public ActionListener[] getActionListeners(){
        return listenerList.getListeners(ActionListener.class);
    }
    /**
     * 
     * @param evt 
     */
    protected void fireActionPerformed(ActionEvent evt){
        for (ActionListener l : getActionListeners()){
            if (l != null)
                l.actionPerformed(evt);
        }
    }
    /**
     * 
     * @param id
     * @param command
     * @param when
     * @param modifiers 
     */
    protected void fireActionPerformed(int id, String command, long when, int 
            modifiers){
        fireActionPerformed(new ActionEvent(this,id,command,when,modifiers));
    }
    /**
     * 
     * @param id
     * @param command 
     */
    protected void fireActionPerformed(int id, String command){
        fireActionPerformed(new ActionEvent(this,id,command));
    }
    /**
     * 
     * @param l 
     */
    public void addChangeListener(ChangeListener l){
            // If the listener is not null
        if (l != null)
            listenerList.add(ChangeListener.class, l);
    }
    /**
     * 
     * @param l 
     */
    public void removeChangeListener(ChangeListener l){
        listenerList.remove(ChangeListener.class, l);
    }
    /**
     * 
     * @return 
     */
    public ChangeListener[] getChangeListeners(){
        return listenerList.getListeners(ChangeListener.class);
    }
    /**
     * 
     */
    protected void fireStateChanged(){
        ChangeEvent evt = new ChangeEvent(this);
        for (ChangeListener l : getChangeListeners()){
            if (l != null)
                l.stateChanged(evt);
        }
    }
    /**
     * 
     * @param l 
     */
    public void addDocumentListener(DocumentListener l){
        if (l != null)
            listenerList.add(DocumentListener.class, l);
    }
    /**
     * 
     * @param l 
     */
    public void removeDocumentListener(DocumentListener l){
        listenerList.remove(DocumentListener.class, l);
    }
    /**
     * 
     * @return 
     */
    public DocumentListener[] getDocumentListeners(){
        return listenerList.getListeners(DocumentListener.class);
    }
    @Override
    protected String paramString(){
        String stateStr = "";
        int state = getState();
        switch(state){
            case(RESULTS_SHOWN_STATE):
                stateStr = "resultsModel="+Objects.toString(getResultsModel(),"");
                break;
            case(UPDATES_SHOWN_STATE):
                stateStr = "updateCount="+Objects.toString(getUpdateCount(),"");
                break;
            case(ERROR_SHOWN_STATE):
                stateStr = "exception="+Objects.toString(getException(), "")+
                        ((getErrorCode()!=null)?",errorCode="+getErrorCode():"");
        }
        return super.paramString()+
                ",executionTime="+getExecutionTime()+
                ",state="+getState()+" ["+stateStr+"]";
    }
    @Override
    public void setEnabled(boolean enabled){
        super.setEnabled(enabled);
        updateExecuteQueryEnabled();
    }
    /**
     * 
     */
    private void updateExecuteQueryEnabled(){
        executeQueryButton.setEnabled(isEnabled() && 
                dbQueryField.getText() != null &&
                !dbQueryField.getText().isBlank());
    }
    /**
     * The time it took to execute the most recent query.
     */
    private long time = 0;
    /**
     * The table model showing the results of the most recent query.
     */
    private TableModel resultsModel = null;
    /**
     * The update count of the most recent query.
     */
    private Integer updateCount = null;
    /**
     * The exception that was thrown during the most recent query.
     */
    private Exception ex = null;
    /**
     * The SQL error code for the exception that was thrown during the most 
     * recent query.
     */
    private Integer errorCode = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dbQueryBlankCard;
    private javax.swing.JLabel dbQueryErrorCodeLabel;
    private javax.swing.JLabel dbQueryErrorLabel;
    private javax.swing.JPanel dbQueryErrorPanel;
    private javax.swing.JTextField dbQueryField;
    private javax.swing.JPanel dbQueryResultsPanel;
    private javax.swing.JScrollPane dbQueryScrollPane;
    private javax.swing.JTable dbQueryTable;
    private javax.swing.JLabel dbQueryTimeLabel;
    private javax.swing.JLabel dbQueryUpdateLabel;
    private javax.swing.JPanel dbQueryUpdatePanel;
    private javax.swing.JButton executeQueryButton;
    private javax.swing.JPopupMenu popupMenu;
    // End of variables declaration//GEN-END:variables
    /**
     * 
     */
    private class Handler implements DocumentListener{
        @Override
        public void insertUpdate(DocumentEvent e) {
            updateExecuteQueryEnabled();
            for (DocumentListener l : getDocumentListeners()){
                if (l != null)
                    l.insertUpdate(e);
            }
        }
        @Override
        public void removeUpdate(DocumentEvent e) {
            updateExecuteQueryEnabled();
            for (DocumentListener l : getDocumentListeners()){
                if (l != null)
                    l.removeUpdate(e);
            }
        }
        @Override
        public void changedUpdate(DocumentEvent e) {
            updateExecuteQueryEnabled();
            for (DocumentListener l : getDocumentListeners()){
                if (l != null)
                    l.changedUpdate(e);
            }
        }
    }
}
