/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manager.database;

/**
 *
 * @author Mosblinker
 */
public class DatabaseQueryTestPanel extends javax.swing.JPanel {

    /**
     * Creates new form DatabaseQueryTestPanel
     */
    public DatabaseQueryTestPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        popupMenu = new javax.swing.JPopupMenu();
        dbQueryField = new javax.swing.JTextField();
        javax.swing.JLabel dbQueryLabel = new javax.swing.JLabel();
        executeQueryButton = new javax.swing.JButton();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        dbQueryTimeLabel = new javax.swing.JLabel();
        dbQueryResultsPanel = new javax.swing.JPanel();
        dbQueryBlankCard = new javax.swing.JLabel();
        dbQueryScrollPane = new javax.swing.JScrollPane();
        dbQueryTable = new javax.swing.JTable();
        dbQueryUpdatePanel = new javax.swing.JPanel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        dbQueryUpdateLabel = new javax.swing.JLabel();
        dbQueryErrorPanel = new javax.swing.JPanel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        dbQueryErrorLabel = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        dbQueryErrorCodeLabel = new javax.swing.JLabel();

        dbQueryLabel.setText("Query:");

        executeQueryButton.setText("Execute");
        executeQueryButton.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Results"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("Time:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        dbQueryTimeLabel.setText("0 ms");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 6, 0, 12);
        jPanel1.add(dbQueryTimeLabel, gridBagConstraints);

        dbQueryResultsPanel.setLayout(new java.awt.CardLayout());

        dbQueryBlankCard.setName("blank"); // NOI18N
        dbQueryResultsPanel.add(dbQueryBlankCard, "blank");

        dbQueryScrollPane.setName("table"); // NOI18N

        dbQueryTable.setAutoCreateRowSorter(true);
        dbQueryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dbQueryScrollPane.setViewportView(dbQueryTable);

        dbQueryResultsPanel.add(dbQueryScrollPane, "table");

        dbQueryUpdatePanel.setName("update"); // NOI18N

        jLabel3.setText("Update Count: ");

        dbQueryUpdateLabel.setText("-1");

        javax.swing.GroupLayout dbQueryUpdatePanelLayout = new javax.swing.GroupLayout(dbQueryUpdatePanel);
        dbQueryUpdatePanel.setLayout(dbQueryUpdatePanelLayout);
        dbQueryUpdatePanelLayout.setHorizontalGroup(
            dbQueryUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbQueryUpdatePanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dbQueryUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dbQueryUpdatePanelLayout.setVerticalGroup(
            dbQueryUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbQueryUpdatePanelLayout.createSequentialGroup()
                .addGroup(dbQueryUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dbQueryUpdateLabel))
                .addGap(0, 177, Short.MAX_VALUE))
        );

        dbQueryResultsPanel.add(dbQueryUpdatePanel, "update");

        dbQueryErrorPanel.setName("error"); // NOI18N

        jLabel6.setText("Error:");

        dbQueryErrorLabel.setText("N/A");

        jLabel10.setText("Error Code:");

        dbQueryErrorCodeLabel.setText("-1");

        javax.swing.GroupLayout dbQueryErrorPanelLayout = new javax.swing.GroupLayout(dbQueryErrorPanel);
        dbQueryErrorPanel.setLayout(dbQueryErrorPanelLayout);
        dbQueryErrorPanelLayout.setHorizontalGroup(
            dbQueryErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbQueryErrorPanelLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dbQueryErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dbQueryErrorPanelLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dbQueryErrorCodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
        );
        dbQueryErrorPanelLayout.setVerticalGroup(
            dbQueryErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbQueryErrorPanelLayout.createSequentialGroup()
                .addGroup(dbQueryErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dbQueryErrorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dbQueryErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(dbQueryErrorCodeLabel))
                .addGap(0, 154, Short.MAX_VALUE))
        );

        dbQueryResultsPanel.add(dbQueryErrorPanel, "error");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.weighty = 0.9;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 13, 12);
        jPanel1.add(dbQueryResultsPanel, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dbQueryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dbQueryField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(executeQueryButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(executeQueryButton)
                    .addComponent(dbQueryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbQueryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dbQueryBlankCard;
    private javax.swing.JLabel dbQueryErrorCodeLabel;
    private javax.swing.JLabel dbQueryErrorLabel;
    private javax.swing.JPanel dbQueryErrorPanel;
    private javax.swing.JTextField dbQueryField;
    private javax.swing.JPanel dbQueryResultsPanel;
    private javax.swing.JScrollPane dbQueryScrollPane;
    private javax.swing.JTable dbQueryTable;
    private javax.swing.JLabel dbQueryTimeLabel;
    private javax.swing.JLabel dbQueryUpdateLabel;
    private javax.swing.JPanel dbQueryUpdatePanel;
    private javax.swing.JButton executeQueryButton;
    private javax.swing.JPopupMenu popupMenu;
    // End of variables declaration//GEN-END:variables
}
