/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package manager.timermenu;

import java.awt.*;

/**
 *
 * @author Milo Steier
 */
public class AutoTimerMenuTester extends javax.swing.JFrame {
    
    protected static final int[] DURATIONS = {
        0,
        500,
        5000,
        10000,
        60000,
        300000,
        305000,
        900000,
        1800000,
        3600000,
        7200000,
        9000000,
        9005000,
    };

    /**
     * Creates new form AutoTimerMenuTester
     */
    public AutoTimerMenuTester() {
        timerMenu1 = new RepeatingTimerMenu();
        timerMenu2 = new NonRepeatingTimerMenu();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        printButton = new javax.swing.JButton();
        menu1Enabled = new javax.swing.JCheckBox();
        menu2Enabled = new javax.swing.JCheckBox();
        menu1Paused = new javax.swing.JCheckBox();
        menu2Paused = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        start1Button = new javax.swing.JButton();
        start2Button = new javax.swing.JButton();
        resume1Button = new javax.swing.JButton();
        resume2Button = new javax.swing.JButton();
        stop1Button = new javax.swing.JButton();
        stop2Button = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu1 = timerMenu1;
        javax.swing.JMenu jMenu2 = timerMenu2;

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        printButton.setText("Print Data");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        menu1Enabled.setSelected(true);
        menu1Enabled.setText("Menu 1 Enabled");
        menu1Enabled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1EnabledActionPerformed(evt);
            }
        });

        menu2Enabled.setSelected(true);
        menu2Enabled.setText("Menu 2 Enabled");
        menu2Enabled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu2EnabledActionPerformed(evt);
            }
        });

        menu1Paused.setText("Timer 1 Paused");
        menu1Paused.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1PausedActionPerformed(evt);
            }
        });

        menu2Paused.setText("Timer 2 Paused");
        menu2Paused.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu2PausedActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 6, 6));

        start1Button.setText("Start Timer 1");
        start1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start1ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(start1Button);

        start2Button.setText("Start Timer 2");
        start2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start2ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(start2Button);

        resume1Button.setText("Resume Timer 1");
        resume1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resume1ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(resume1Button);

        resume2Button.setText("Resume Timer 2");
        resume2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resume2ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(resume2Button);

        stop1Button.setText("Stop Timer 1");
        stop1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stop1ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(stop1Button);

        stop2Button.setText("Stop Timer 2");
        stop2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stop2ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(stop2Button);

        jMenu1.setName("Menu 1"); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerMenuActionPerformed(evt);
            }
        });
        jMenu1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                timerMenuPropertyChange(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setName("Menu 2"); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerMenuActionPerformed(evt);
            }
        });
        jMenu2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                timerMenuPropertyChange(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(printButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menu2Enabled)
                            .addComponent(menu1Enabled))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menu1Paused)
                            .addComponent(menu2Paused)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menu1Paused)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(menu2Paused))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(printButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(menu1Enabled)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(menu2Enabled)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        for (AutoTimerMenu menu : new AutoTimerMenu[]{timerMenu1,timerMenu2}){
            System.out.println(menu.getName() + ": ");
            System.out.println("\ttoString(): "+menu.toString());
            System.out.println("\tRunning: " + menu.isRunning());
            System.out.println("\tWas Running: "+menu.wasRunning());
            System.out.println("\tPaused: " + menu.isPaused());
            System.out.println("\tEnabled: " + menu.isEnabled());
            System.out.println("\tDuration Index: " + menu.getDurationIndex());
            System.out.println("\tDuration: " + menu.getDuration());
            System.out.println("\tTimer Delay: " + menu.getTimer().getDelay());
            System.out.println("\tTimer Initial Delay: " + menu.getTimer().getInitialDelay());
            System.out.println("\tStartable: " + menu.isStartable());
            System.out.println("\tRepeating: " + menu.isRepeating());
            System.out.println();
        }
    }//GEN-LAST:event_printButtonActionPerformed

    private void menu1EnabledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1EnabledActionPerformed
        timerMenu1.setEnabled(menu1Enabled.isSelected());
    }//GEN-LAST:event_menu1EnabledActionPerformed

    private void menu2EnabledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu2EnabledActionPerformed
        timerMenu2.setEnabled(menu2Enabled.isSelected());
    }//GEN-LAST:event_menu2EnabledActionPerformed

    private void timerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timerMenuActionPerformed
        if (evt.getSource() instanceof Component)
            System.out.print(((Component)evt.getSource()).getName()+": ");
        System.out.println(evt.getActionCommand() + " " + evt);
    }//GEN-LAST:event_timerMenuActionPerformed

    private void timerMenuPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_timerMenuPropertyChange
        if (evt.getSource() instanceof Component)
            System.out.print(((Component)evt.getSource()).getName()+": ");
        System.out.println(evt);
    }//GEN-LAST:event_timerMenuPropertyChange

    private void menu1PausedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1PausedActionPerformed
        timerMenu1.setPaused(menu1Paused.isSelected());
    }//GEN-LAST:event_menu1PausedActionPerformed

    private void menu2PausedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu2PausedActionPerformed
        timerMenu2.setPaused(menu2Paused.isSelected());
    }//GEN-LAST:event_menu2PausedActionPerformed

    private void start1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start1ButtonActionPerformed
        timerMenu1.startTimer();
    }//GEN-LAST:event_start1ButtonActionPerformed

    private void resume1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resume1ButtonActionPerformed
        timerMenu1.resumeTimer();
    }//GEN-LAST:event_resume1ButtonActionPerformed

    private void stop1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stop1ButtonActionPerformed
        timerMenu1.stopTimer();
    }//GEN-LAST:event_stop1ButtonActionPerformed

    private void start2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start2ButtonActionPerformed
        timerMenu2.startTimer();
    }//GEN-LAST:event_start2ButtonActionPerformed

    private void resume2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resume2ButtonActionPerformed
        timerMenu2.resumeTimer();
    }//GEN-LAST:event_resume2ButtonActionPerformed

    private void stop2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stop2ButtonActionPerformed
        timerMenu2.stopTimer();
    }//GEN-LAST:event_stop2ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoTimerMenuTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoTimerMenuTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoTimerMenuTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoTimerMenuTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoTimerMenuTester().setVisible(true);
            }
        });
    }
    
    private RepeatingTimerMenu timerMenu1;
    private NonRepeatingTimerMenu timerMenu2;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox menu1Enabled;
    private javax.swing.JCheckBox menu1Paused;
    private javax.swing.JCheckBox menu2Enabled;
    private javax.swing.JCheckBox menu2Paused;
    private javax.swing.JButton printButton;
    private javax.swing.JButton resume1Button;
    private javax.swing.JButton resume2Button;
    private javax.swing.JButton start1Button;
    private javax.swing.JButton start2Button;
    private javax.swing.JButton stop1Button;
    private javax.swing.JButton stop2Button;
    // End of variables declaration//GEN-END:variables

    private abstract class TimerMenu extends AutoTimerMenu{
        
        public TimerMenu(String text, int index){
            super(text,index);
        }
        
        public TimerMenu(String text){
            super(text);
        }
        
        @Override
        protected int[] getDurations() {
            return DURATIONS;
        }
        @Override
        protected String getTimerCommand() {
            return "Timer";
        }

        @Override
        protected String getDurationCommandPrefix() {
            return "Duration";
        }
        
        @Override
        protected abstract boolean isRepeating();
        
        @Override
        protected String getDurationTextPrefix(){
            return (isRepeating()) ? "Every " : "After ";
        }
    }
    
    private class RepeatingTimerMenu extends TimerMenu{
        
        public RepeatingTimerMenu(){
            super("Menu 1");
        }
        @Override
        protected boolean isRepeating() {
            return true;
        }
        @Override
        protected String getDuration0Text(){
            return "Off";
        }
    }
    
    private class NonRepeatingTimerMenu extends TimerMenu{
        
        public NonRepeatingTimerMenu(){
            super("Menu 2", 2);
        }
        @Override
        protected boolean isRepeating() {
            return false;
        }
    }
}
